
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.minebound.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.biome.Biome;

import net.mcreator.minebound.world.biome.WildernessUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.VolcanicDecayedBiomeBiome;
import net.mcreator.minebound.world.biome.VolcanicBiomeBiome;
import net.mcreator.minebound.world.biome.TundraSnowBiomeBiome;
import net.mcreator.minebound.world.biome.TundraBiomeBiome;
import net.mcreator.minebound.world.biome.ToxicOceanBiome;
import net.mcreator.minebound.world.biome.ToxicBiomeBiome;
import net.mcreator.minebound.world.biome.TentacleBiomeBiome;
import net.mcreator.minebound.world.biome.TarpitUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.TarMiniBiomeBiome;
import net.mcreator.minebound.world.biome.SwampMiniBiomeBiome;
import net.mcreator.minebound.world.biome.StoneCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.SteamSpringMiniBiomeBiome;
import net.mcreator.minebound.world.biome.SpringMiniBiomeBiome;
import net.mcreator.minebound.world.biome.SnowGardenBiomeBiome;
import net.mcreator.minebound.world.biome.SnowBiomeBiome;
import net.mcreator.minebound.world.biome.SlimeCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.SavannahBiomeBiome;
import net.mcreator.minebound.world.biome.SavannaDesertBiomeBiome;
import net.mcreator.minebound.world.biome.PrismMiniBiomeBiome;
import net.mcreator.minebound.world.biome.OceanBiomeBiome;
import net.mcreator.minebound.world.biome.OceanBiome;
import net.mcreator.minebound.world.biome.OasisMiniBiomeBiome;
import net.mcreator.minebound.world.biome.NoSnowHighUpBiomeBiome;
import net.mcreator.minebound.world.biome.MutatedSavannahBiomeBiome;
import net.mcreator.minebound.world.biome.MutatedBiomeBiome;
import net.mcreator.minebound.world.biome.MushroomsUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.MushroomPatchMiniBiomeBiome;
import net.mcreator.minebound.world.biome.MoonTemperateBiomeBiome;
import net.mcreator.minebound.world.biome.MoonRadioactiveBiomeBiome;
import net.mcreator.minebound.world.biome.MoonGentleBiomeBiome;
import net.mcreator.minebound.world.biome.MoonFrozenBiomeBiome;
import net.mcreator.minebound.world.biome.MoonFieryBiomeBiome;
import net.mcreator.minebound.world.biome.MoonBiomeBiome;
import net.mcreator.minebound.world.biome.MiniVillageUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.MidnightTundraBiomeBiome;
import net.mcreator.minebound.world.biome.MidnightBiomeBiome;
import net.mcreator.minebound.world.biome.MagmaoceanBiome;
import net.mcreator.minebound.world.biome.MagmaBiomeBiome;
import net.mcreator.minebound.world.biome.LuminousCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.JungleMutatedBiomeBiome;
import net.mcreator.minebound.world.biome.JungleBiomeBiome;
import net.mcreator.minebound.world.biome.IceCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.HiveMiniBiomeBiome;
import net.mcreator.minebound.world.biome.GiantFlowersMiniBiomeBiome;
import net.mcreator.minebound.world.biome.GeodeMiniBiomeBiome;
import net.mcreator.minebound.world.biome.GasGiantBiomeBiome;
import net.mcreator.minebound.world.biome.GardenForestBiomeBiome;
import net.mcreator.minebound.world.biome.GardenBiomeBiome;
import net.mcreator.minebound.world.biome.FoundryMiniBiomeBiome;
import net.mcreator.minebound.world.biome.ForestJungleBiomeBiome;
import net.mcreator.minebound.world.biome.ForestBiomeBiome;
import net.mcreator.minebound.world.biome.FleshMiniBiomeBiome;
import net.mcreator.minebound.world.biome.FleshCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.EyepatchMiniBiomeBiome;
import net.mcreator.minebound.world.biome.EmptyspaceBiome;
import net.mcreator.minebound.world.biome.EmptySpaceBiomeBiome;
import net.mcreator.minebound.world.biome.DesertBiomeBiome;
import net.mcreator.minebound.world.biome.DesertBarrenBiomeBiome;
import net.mcreator.minebound.world.biome.DepthTestBiome6Biome;
import net.mcreator.minebound.world.biome.DepthTestBiome5Biome;
import net.mcreator.minebound.world.biome.DepthTestBiome4Biome;
import net.mcreator.minebound.world.biome.DepthTestBiome3Biome;
import net.mcreator.minebound.world.biome.DepthTestBiome2Biome;
import net.mcreator.minebound.world.biome.DepthTestBiome1Biome;
import net.mcreator.minebound.world.biome.DecayedVolcanicBiomeBiome;
import net.mcreator.minebound.world.biome.DecayedBiomeBiome;
import net.mcreator.minebound.world.biome.ColourfulMiniBiomeBiome;
import net.mcreator.minebound.world.biome.CellCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.BrainUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.BonesMiniBiomeBiome;
import net.mcreator.minebound.world.biome.BoneCavesUndergroundBiomeBiome;
import net.mcreator.minebound.world.biome.BioluminescenceMiniBiomeBiome;
import net.mcreator.minebound.world.biome.BarrenBiomeBiome;
import net.mcreator.minebound.world.biome.AsteroidsMiniBiomeBiome;
import net.mcreator.minebound.world.biome.AsteroidFieldBiomeBiome;
import net.mcreator.minebound.world.biome.ArticoceanBiome;
import net.mcreator.minebound.world.biome.ArcticBiomeBiome;
import net.mcreator.minebound.world.biome.AncientVaultBiomeBiome;
import net.mcreator.minebound.world.biome.AlpineMiniBiomeBiome;
import net.mcreator.minebound.MineboundMod;

public class MineboundModBiomes {
	public static final DeferredRegister<Biome> REGISTRY = DeferredRegister.create(ForgeRegistries.BIOMES, MineboundMod.MODID);
	public static final RegistryObject<Biome> EMPTYSPACE = REGISTRY.register("emptyspace", EmptyspaceBiome::createBiome);
	public static final RegistryObject<Biome> NO_SNOW_HIGH_UP_BIOME = REGISTRY.register("no_snow_high_up_biome", NoSnowHighUpBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MOON_BIOME = REGISTRY.register("moon_biome", MoonBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TOXIC_OCEAN = REGISTRY.register("toxic_ocean", ToxicOceanBiome::createBiome);
	public static final RegistryObject<Biome> OCEAN = REGISTRY.register("ocean", OceanBiome::createBiome);
	public static final RegistryObject<Biome> DEPTH_TEST_BIOME_1 = REGISTRY.register("depth_test_biome_1", DepthTestBiome1Biome::createBiome);
	public static final RegistryObject<Biome> DEPTH_TEST_BIOME_2 = REGISTRY.register("depth_test_biome_2", DepthTestBiome2Biome::createBiome);
	public static final RegistryObject<Biome> MAGMAOCEAN = REGISTRY.register("magmaocean", MagmaoceanBiome::createBiome);
	public static final RegistryObject<Biome> DEPTH_TEST_BIOME_3 = REGISTRY.register("depth_test_biome_3", DepthTestBiome3Biome::createBiome);
	public static final RegistryObject<Biome> DEPTH_TEST_BIOME_4 = REGISTRY.register("depth_test_biome_4", DepthTestBiome4Biome::createBiome);
	public static final RegistryObject<Biome> ARTICOCEAN = REGISTRY.register("articocean", ArticoceanBiome::createBiome);
	public static final RegistryObject<Biome> DEPTH_TEST_BIOME_5 = REGISTRY.register("depth_test_biome_5", DepthTestBiome5Biome::createBiome);
	public static final RegistryObject<Biome> DEPTH_TEST_BIOME_6 = REGISTRY.register("depth_test_biome_6", DepthTestBiome6Biome::createBiome);
	public static final RegistryObject<Biome> ANCIENT_VAULT_BIOME = REGISTRY.register("ancient_vault_biome", AncientVaultBiomeBiome::createBiome);
	public static final RegistryObject<Biome> GARDEN_BIOME = REGISTRY.register("garden_biome", GardenBiomeBiome::createBiome);
	public static final RegistryObject<Biome> DESERT_BIOME = REGISTRY.register("desert_biome", DesertBiomeBiome::createBiome);
	public static final RegistryObject<Biome> FOREST_BIOME = REGISTRY.register("forest_biome", ForestBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SAVANNAH_BIOME = REGISTRY.register("savannah_biome", SavannahBiomeBiome::createBiome);
	public static final RegistryObject<Biome> OCEAN_BIOME = REGISTRY.register("ocean_biome", OceanBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SNOW_BIOME = REGISTRY.register("snow_biome", SnowBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MUTATED_BIOME = REGISTRY.register("mutated_biome", MutatedBiomeBiome::createBiome);
	public static final RegistryObject<Biome> JUNGLE_BIOME = REGISTRY.register("jungle_biome", JungleBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TOXIC_BIOME = REGISTRY.register("toxic_biome", ToxicBiomeBiome::createBiome);
	public static final RegistryObject<Biome> ARCTIC_BIOME = REGISTRY.register("arctic_biome", ArcticBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TUNDRA_BIOME = REGISTRY.register("tundra_biome", TundraBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MIDNIGHT_BIOME = REGISTRY.register("midnight_biome", MidnightBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MAGMA_BIOME = REGISTRY.register("magma_biome", MagmaBiomeBiome::createBiome);
	public static final RegistryObject<Biome> VOLCANIC_BIOME = REGISTRY.register("volcanic_biome", VolcanicBiomeBiome::createBiome);
	public static final RegistryObject<Biome> DECAYED_BIOME = REGISTRY.register("decayed_biome", DecayedBiomeBiome::createBiome);
	public static final RegistryObject<Biome> ASTEROID_FIELD_BIOME = REGISTRY.register("asteroid_field_biome", AsteroidFieldBiomeBiome::createBiome);
	public static final RegistryObject<Biome> BARREN_BIOME = REGISTRY.register("barren_biome", BarrenBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TENTACLE_BIOME = REGISTRY.register("tentacle_biome", TentacleBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MOON_GENTLE_BIOME = REGISTRY.register("moon_gentle_biome", MoonGentleBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MOON_TEMPERATE_BIOME = REGISTRY.register("moon_temperate_biome", MoonTemperateBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MOON_RADIOACTIVE_BIOME = REGISTRY.register("moon_radioactive_biome", MoonRadioactiveBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MOON_FROZEN_BIOME = REGISTRY.register("moon_frozen_biome", MoonFrozenBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MOON_FIERY_BIOME = REGISTRY.register("moon_fiery_biome", MoonFieryBiomeBiome::createBiome);
	public static final RegistryObject<Biome> GARDEN_FOREST_BIOME = REGISTRY.register("garden_forest_biome", GardenForestBiomeBiome::createBiome);
	public static final RegistryObject<Biome> DESERT_BARREN_BIOME = REGISTRY.register("desert_barren_biome", DesertBarrenBiomeBiome::createBiome);
	public static final RegistryObject<Biome> FOREST_JUNGLE_BIOME = REGISTRY.register("forest_jungle_biome", ForestJungleBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SAVANNA_DESERT_BIOME = REGISTRY.register("savanna_desert_biome", SavannaDesertBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SNOW_GARDEN_BIOME = REGISTRY.register("snow_garden_biome", SnowGardenBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MUTATED_SAVANNAH_BIOME = REGISTRY.register("mutated_savannah_biome", MutatedSavannahBiomeBiome::createBiome);
	public static final RegistryObject<Biome> JUNGLE_MUTATED_BIOME = REGISTRY.register("jungle_mutated_biome", JungleMutatedBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TUNDRA_SNOW_BIOME = REGISTRY.register("tundra_snow_biome", TundraSnowBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MIDNIGHT_TUNDRA_BIOME = REGISTRY.register("midnight_tundra_biome", MidnightTundraBiomeBiome::createBiome);
	public static final RegistryObject<Biome> VOLCANIC_DECAYED_BIOME = REGISTRY.register("volcanic_decayed_biome", VolcanicDecayedBiomeBiome::createBiome);
	public static final RegistryObject<Biome> DECAYED_VOLCANIC_BIOME = REGISTRY.register("decayed_volcanic_biome", DecayedVolcanicBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SPRING_MINI_BIOME = REGISTRY.register("spring_mini_biome", SpringMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> OASIS_MINI_BIOME = REGISTRY.register("oasis_mini_biome", OasisMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MUSHROOM_PATCH_MINI_BIOME = REGISTRY.register("mushroom_patch_mini_biome", MushroomPatchMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SWAMP_MINI_BIOME = REGISTRY.register("swamp_mini_biome", SwampMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> BONES_MINI_BIOME = REGISTRY.register("bones_mini_biome", BonesMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> COLOURFUL_MINI_BIOME = REGISTRY.register("colourful_mini_biome", ColourfulMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> ALPINE_MINI_BIOME = REGISTRY.register("alpine_mini_biome", AlpineMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> FLESH_MINI_BIOME = REGISTRY.register("flesh_mini_biome", FleshMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TAR_MINI_BIOME = REGISTRY.register("tar_mini_biome", TarMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> GIANT_FLOWERS_MINI_BIOME = REGISTRY.register("giant_flowers_mini_biome", GiantFlowersMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> EYEPATCH_MINI_BIOME = REGISTRY.register("eyepatch_mini_biome", EyepatchMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> PRISM_MINI_BIOME = REGISTRY.register("prism_mini_biome", PrismMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> STEAM_SPRING_MINI_BIOME = REGISTRY.register("steam_spring_mini_biome", SteamSpringMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> HIVE_MINI_BIOME = REGISTRY.register("hive_mini_biome", HiveMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> BIOLUMINESCENCE_MINI_BIOME = REGISTRY.register("bioluminescence_mini_biome", BioluminescenceMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> GEODE_MINI_BIOME = REGISTRY.register("geode_mini_biome", GeodeMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> FOUNDRY_MINI_BIOME = REGISTRY.register("foundry_mini_biome", FoundryMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> ASTEROIDS_MINI_BIOME = REGISTRY.register("asteroids_mini_biome", AsteroidsMiniBiomeBiome::createBiome);
	public static final RegistryObject<Biome> BONE_CAVES_UNDERGROUND_BIOME = REGISTRY.register("bone_caves_underground_biome", BoneCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> CELL_CAVES_UNDERGROUND_BIOME = REGISTRY.register("cell_caves_underground_biome", CellCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> FLESH_CAVES_UNDERGROUND_BIOME = REGISTRY.register("flesh_caves_underground_biome", FleshCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> ICE_CAVES_UNDERGROUND_BIOME = REGISTRY.register("ice_caves_underground_biome", IceCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> LUMINOUS_CAVES_UNDERGROUND_BIOME = REGISTRY.register("luminous_caves_underground_biome", LuminousCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MINI_VILLAGE_UNDERGROUND_BIOME = REGISTRY.register("mini_village_underground_biome", MiniVillageUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> MUSHROOMS_UNDERGROUND_BIOME = REGISTRY.register("mushrooms_underground_biome", MushroomsUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> SLIME_CAVES_UNDERGROUND_BIOME = REGISTRY.register("slime_caves_underground_biome", SlimeCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> STONE_CAVES_UNDERGROUND_BIOME = REGISTRY.register("stone_caves_underground_biome", StoneCavesUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> TARPIT_UNDERGROUND_BIOME = REGISTRY.register("tarpit_underground_biome", TarpitUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> WILDERNESS_UNDERGROUND_BIOME = REGISTRY.register("wilderness_underground_biome", WildernessUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> BRAIN_UNDERGROUND_BIOME = REGISTRY.register("brain_underground_biome", BrainUndergroundBiomeBiome::createBiome);
	public static final RegistryObject<Biome> EMPTY_SPACE_BIOME = REGISTRY.register("empty_space_biome", EmptySpaceBiomeBiome::createBiome);
	public static final RegistryObject<Biome> GAS_GIANT_BIOME = REGISTRY.register("gas_giant_biome", GasGiantBiomeBiome::createBiome);
}
